require:
  rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'report/**/*'

# Layout and Style Configuration
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'lib/dev_metrics/cli/runner.rb' # Help text contains long lines

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/ClassLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 17
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Fix deprecated RSpec configurations
RSpec/MultipleExpectations:
  Max: 2

RSpec/MultipleMemoizedHelpers:
  Max: 5

Capybara/RSpec/PredicateMatcher:
  Enabled: false